# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8f5606db679ee1ff912944ce2a56e81cfe491ceabfab34f66ed708d5ab47cf7110b7c56ef497f9ef678b65b06adb95ee902118fd6e138c658118c14994ac4ca

test:
  secret_key_base: 2d9b2a84ca8a221c3edf2217e2c074a4107c7015ff6205023973a6b8efffb5f7bc359b1af0dcc10288442fda8136b1ff3d1c80f62dbd66f95028fe4eddabb5ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
